dist: trusty
branches:
  only:
    - stable
    - beta
    - beta5
    - feature/beta/.*

language: node_js
node_js:
  - 12

install:
  - npm install

jobs:
  include:
    - name: 'Lint SCSS files'
      script: npm run lint
    - name: 'Run test scripts'
      script: npm run test